### ISSUE TITLE
Servidor indisponível

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_backoffice#1]
Quando tento acessar a plataforma apresenta o erro de servidor temporariamente indisponível.
image.

![a8d77d3a-c66a-11e5-84e0-b47595b2bc9e](https://cloud.githubusercontent.com/assets/504142/12674839/30c71f1e-c66d-11e5-968d-8f8d54ee3474.png)

**Comment by leobueno** [comment]
O servidor estava parado para manutenção de hardware. Apenas o front-end, que está em outro servidor, estava no ar.

O servidor já foi reiniciado e está disponível.
