### ISSUE TITLE
Problema na seleção de imagem

### ISSUE THREAD

**Issue by javani** [scieloorg/pulsemob_backoffice#15]
Quando seleciono a imagem, o quadro onde a mesma deveria aparecer fica em branco. Mesmo assim, é possível salvá-la e a mesma aparece no dashboard como se a capa estivesse disponível.
Saí e entrei no aplicativo e problema persiste.
![image](https://cloud.githubusercontent.com/assets/912953/12714859/0fe51fe6-c8be-11e5-854b-53168ff77936.png)

**Comment by ghost** [comment]
@javani você poderia me mandar a imagem que está tentando inserir? Imagino que possa ser algum problema com o formato dela. O que está salvo no servidor é, na verdade, uma imagem vazia no formato png.

**Comment by javani** [comment]
@carlosecbraga não lembro mais qual imagem eu subi, mas testei com outras e está ok agora. Acredito que podemos fechar esse ticket.
