### ISSUE TITLE
Lista de categorias sem conteúdo

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_backoffice#18]
Aparentemente esta faltando algo para que as categorias sejam apresentadas.

![screen shot 2016-03-22 at 1 54 38 pm](https://cloud.githubusercontent.com/assets/504142/13960128/c6772148-f035-11e5-9132-4042a7fc1e8a.png)

**Comment by ghost** [comment]
O serviço utilizado traz os artigos com informações de categoria apenas em inglês e no backoffice utilizamos na interface os termos em português. Porém, precisamos popular o banco com essas informações manualmente. Vou atualizar a documentação.

**Comment by fabiobatalha** [comment]
Incluídos registros em base de dados.

UPDATE common_category SET category_name_pt='Ciências Biológicas', category_name_es='Ciencias Biológicas' WHERE id = 1;
UPDATE common_category SET category_name_pt='Ciências da Saúde', category_name_es='Ciencias de la Salud' WHERE id = 2;
UPDATE common_category SET category_name_pt='Engenharias', category_name_es='Ingenierias' WHERE id = 3;
UPDATE common_category SET category_name_pt='Ciências Sociais Aplicadas', category_name_es='Ciencias Sociales Aplicadas' WHERE id = 4;
UPDATE common_category SET category_name_pt='Ciências Humanas', category_name_es='Humanidades' WHERE id = 5;
UPDATE common_category SET category_name_pt='Ciências Exatas e da Terra', category_name_es='Ciencias Exactas y de la Tierra' WHERE id = 6;
UPDATE common_category SET category_name_pt='Ciências Agrárias', category_name_es='Ciencias Agrícolas' WHERE id = 7;
UPDATE common_category SET category_name_pt='Lingüística, Letras e Artes', category_name_es='Lingüistica, Letras y Artes' WHERE id = 8;
