### ISSUE TITLE
Carga de imagem não salva imagem no artigo

### ISSUE THREAD

**Issue by javani** [scieloorg/pulsemob_backoffice#2]
Ao tentar salvar imagem, não segue o processo e apresenta erro.
![image](https://cloud.githubusercontent.com/assets/912953/12676431/629701d8-c679-11e5-8bb3-f9ea5bcdc58f.png)

**Comment by fabiobatalha** [comment]
@javani 

Eu consegui salvar uma imagem para um artigo, você pode testar novamente.

**Comment by javani** [comment]
Agora funcionou.

**Comment by javani** [comment]
Começou novamente com esse problema. Já saí e entrei na ferramenta algumas vezes e o erro persiste.
