### ISSUE TITLE
Visualização truncada no dashboard 

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_backoffice#8]
No segundo modelo de visualização do dashboard as imagens começam a truncar quando as caixas têm tamanhos diferentes. Isso deixa a visualização poluída.

Exemplo 1:

![screen shot 2016-01-29 at 2 15 06 pm](https://cloud.githubusercontent.com/assets/504142/12680865/12ec3abc-c693-11e5-8f09-54514d980c6b.png)

Exemplo 2:

![screen shot 2016-01-29 at 2 18 39 pm](https://cloud.githubusercontent.com/assets/504142/12680907/432115ea-c693-11e5-9cd8-9c33dd6d3a88.png)

**Comment by leobueno** [comment]
Acho que não está truncando, os boxes estão apenas ficando desalinhados. Para que isto não ocorra eu vejo 2 alternativas:
- Truncar o título/autores do artigo: Isto deixaria o texto com altura uniforme e os boxes ficariam alinhados
- Adicionar "padding": Isto também alinharia os boxes, mas deixaria espaço em branco não utilizado

Minha sugestão é deixar como está, visto que as duas alternativas acima tem seus pontos negativos também.

O que acha? Prefere truncar ou adicionar padding? Vê alguma outra alternativa?

**Comment by fabiobatalha** [comment]
Por mim podemos deixar como está. Vou verificar com o pessoal que utilizará a ferramenta.
