### ISSUE TITLE
Texto de políticas de uso.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_backoffice#9]
Texto de políticas de uso do Backoffice.

**Comment by leobueno** [comment]
Poderiam enviar o texto?

**Comment by fabiobatalha** [comment]
Declaração de responsabilidade

Os conteúdos publicados pelos periódicos indexados no SciELO, sejam textos, tabelas e qualquer tipo de imagem que fazem parte dos artigos assim como os que ilustram as capas de números, são disponibilizados online em Acesso Aberto.

Cabe a cada periódico adotar uma licença que define as permissões e restrições ao uso dos seus conteúdos. As licenças recomendadas pelo SciELO são as padronizadas pelo sistema Creative Commons. 

Os usuários que acessam, fazem downloads e diferentes usos de conteúdos dos artigos ou das capas dos periódicos SciELO devem obedecer as permissões e restrições estabelecidas pela licença Creative Commons adotada pelo periódico.

Esta ferramenta permite às equipes editoriais dos periódicos SciELO vincular imagens às telas de disseminação de artigos que é feita pelo aplicativo SciELO Mobile. As licenças de uso das imagens selecionadas devem devem estar em correspondência com as licenças de uso adotadas pelos periódicos. O SciELO recomenda o uso autorizado de conteúdos e imagens de propriedade dos periódico ou dos autores dos artigos ou de fontes de informação e bancos de imagens que fornecem a autorização adequada de uso.

A responsabilidade sobre o direito de disponibilizar os conteúdos dos artigos, das capas de números e de disseminação em correspondência com a licença Creative Commons adotada pelo periódico é do editor do periódico e autores dos artigos inclusive sobre o uso de conteúdos de terceiros. Não cabendo ao SciELO nenhum tipo de responsabilidade sobre qualquer uso indevido de  qualquer tipo de conteúdo, sejam texto, tabelas, imagens, etc..

Ao prosseguir com o meu registro para disponibilizar imagens para a  disseminação de artigos e números de periódicos para o aplicativo SciELO Mobile manifesto que estou ciente das condições acima.

```
                                           [não estou de acordo]  [ estou de acordo ]  
```

**Comment by ghost** [comment]
Feito.
